# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Aditi Vijayan
tagline:          'Research Scientist | Arizona State University'
description:      'A computational astrophysicist researching galaxy formation and evolution.'
url:              http://hyde.getpoole.com
baseurl:          ""

author:
  name:           'Aditi Vijayan'
  url:            https://twitter.com/aditivijayan

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/aditivijayan

# Collections
collections:
  random:
    output: true
    permalink: /random/:name/
